language: go
go_import_path: aqwari.net/xml
go:
  - "1.9"
  - "1.10"
  - "1.11"

install:
  # While this package supports Go 1.9+, stringer does not. We need newer
  # versions of Go to check generated files.
  - gimme 1.11
  - source ~/.gimme/envs/go1.11.env
  - go get -t -v ./...
  - go get -v golang.org/x/tools/cmd/stringer

before_script:
  - source ~/.gimme/envs/go1.11.env
  - go generate ./...
  - if [[ -n $(git status -s) ]]; then echo "Unclean working tree"; git diff; exit 1; fi

notifications:
  email:
    recipients: droyo@aqwari.net
    on_success: change
    on_failure: always
